/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AbortedTaskStatus
 */
export interface AbortedTaskStatus {
    /**
     * 
     * @type {any}
     * @memberof AbortedTaskStatus
     */
    cleanUp: any | null;
    /**
     * 
     * @type {string}
     * @memberof AbortedTaskStatus
     */
    status: AbortedTaskStatusStatusEnum;
}


/**
 * @export
 */
export const AbortedTaskStatusStatusEnum = {
    Aborted: 'aborted'
} as const;
export type AbortedTaskStatusStatusEnum = typeof AbortedTaskStatusStatusEnum[keyof typeof AbortedTaskStatusStatusEnum];


/**
 * Check if a given object implements the AbortedTaskStatus interface.
 */
export function instanceOfAbortedTaskStatus(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "cleanUp" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function AbortedTaskStatusFromJSON(json: any): AbortedTaskStatus {
    return AbortedTaskStatusFromJSONTyped(json, false);
}

export function AbortedTaskStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AbortedTaskStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cleanUp': json['cleanUp'],
        'status': json['status'],
    };
}

export function AbortedTaskStatusToJSON(value?: AbortedTaskStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cleanUp': value.cleanUp,
        'status': value.status,
    };
}

