/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthCodeResponse
 */
export interface AuthCodeResponse {
    /**
     * 
     * @type {string}
     * @memberof AuthCodeResponse
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof AuthCodeResponse
     */
    sessionState: string;
    /**
     * 
     * @type {string}
     * @memberof AuthCodeResponse
     */
    state: string;
}

/**
 * Check if a given object implements the AuthCodeResponse interface.
 */
export function instanceOfAuthCodeResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;
    isInstance = isInstance && "sessionState" in value;
    isInstance = isInstance && "state" in value;

    return isInstance;
}

export function AuthCodeResponseFromJSON(json: any): AuthCodeResponse {
    return AuthCodeResponseFromJSONTyped(json, false);
}

export function AuthCodeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthCodeResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'sessionState': json['sessionState'],
        'state': json['state'],
    };
}

export function AuthCodeResponseToJSON(value?: AuthCodeResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'sessionState': value.sessionState,
        'state': value.state,
    };
}

