/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    DerivedColorWithType,
    instanceOfDerivedColorWithType,
    DerivedColorWithTypeFromJSON,
    DerivedColorWithTypeFromJSONTyped,
    DerivedColorWithTypeToJSON,
} from './DerivedColorWithType';
import {
    StaticColorParam,
    instanceOfStaticColorParam,
    StaticColorParamFromJSON,
    StaticColorParamFromJSONTyped,
    StaticColorParamToJSON,
} from './StaticColorParam';

/**
 * @type ColorParam
 * 
 * @export
 */
export type ColorParam = { type: 'derived' } & DerivedColorWithType | { type: 'static' } & StaticColorParam;

export function ColorParamFromJSON(json: any): ColorParam {
    return ColorParamFromJSONTyped(json, false);
}

export function ColorParamFromJSONTyped(json: any, ignoreDiscriminator: boolean): ColorParam {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    switch (json['type']) {
        case 'derived':
            return {...DerivedColorWithTypeFromJSONTyped(json, true), type: 'derived'};
        case 'static':
            return {...StaticColorParamFromJSONTyped(json, true), type: 'static'};
        default:
            throw new Error(`No variant of ColorParam exists with 'type=${json['type']}'`);
    }
}

export function ColorParamToJSON(value?: ColorParam | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    switch (value['type']) {
        case 'derived':
            return DerivedColorWithTypeToJSON(value);
        case 'static':
            return StaticColorParamToJSON(value);
        default:
            throw new Error(`No variant of ColorParam exists with 'type=${value['type']}'`);
    }

}

