/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContinuousMeasurement
 */
export interface ContinuousMeasurement {
    /**
     * 
     * @type {string}
     * @memberof ContinuousMeasurement
     */
    measurement: string;
    /**
     * 
     * @type {string}
     * @memberof ContinuousMeasurement
     */
    unit?: string | null;
}

/**
 * Check if a given object implements the ContinuousMeasurement interface.
 */
export function instanceOfContinuousMeasurement(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "measurement" in value;

    return isInstance;
}

export function ContinuousMeasurementFromJSON(json: any): ContinuousMeasurement {
    return ContinuousMeasurementFromJSONTyped(json, false);
}

export function ContinuousMeasurementFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContinuousMeasurement {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'measurement': json['measurement'],
        'unit': !exists(json, 'unit') ? undefined : json['unit'],
    };
}

export function ContinuousMeasurementToJSON(value?: ContinuousMeasurement | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'measurement': value.measurement,
        'unit': value.unit,
    };
}

