/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataPathOneOf1
 */
export interface DataPathOneOf1 {
    /**
     * 
     * @type {string}
     * @memberof DataPathOneOf1
     */
    upload: string;
}

/**
 * Check if a given object implements the DataPathOneOf1 interface.
 */
export function instanceOfDataPathOneOf1(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "upload" in value;

    return isInstance;
}

export function DataPathOneOf1FromJSON(json: any): DataPathOneOf1 {
    return DataPathOneOf1FromJSONTyped(json, false);
}

export function DataPathOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): DataPathOneOf1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'upload': json['upload'],
    };
}

export function DataPathOneOf1ToJSON(value?: DataPathOneOf1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'upload': value.upload,
    };
}

