/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Colorizer } from './Colorizer';
import {
    ColorizerFromJSON,
    ColorizerFromJSONTyped,
    ColorizerToJSON,
} from './Colorizer';

/**
 * 
 * @export
 * @interface DerivedColorWithType
 */
export interface DerivedColorWithType {
    /**
     * 
     * @type {string}
     * @memberof DerivedColorWithType
     */
    attribute: string;
    /**
     * 
     * @type {Colorizer}
     * @memberof DerivedColorWithType
     */
    colorizer: Colorizer;
    /**
     * 
     * @type {string}
     * @memberof DerivedColorWithType
     */
    type: DerivedColorWithTypeTypeEnum;
}


/**
 * @export
 */
export const DerivedColorWithTypeTypeEnum = {
    Derived: 'derived'
} as const;
export type DerivedColorWithTypeTypeEnum = typeof DerivedColorWithTypeTypeEnum[keyof typeof DerivedColorWithTypeTypeEnum];


/**
 * Check if a given object implements the DerivedColorWithType interface.
 */
export function instanceOfDerivedColorWithType(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "attribute" in value;
    isInstance = isInstance && "colorizer" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function DerivedColorWithTypeFromJSON(json: any): DerivedColorWithType {
    return DerivedColorWithTypeFromJSONTyped(json, false);
}

export function DerivedColorWithTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DerivedColorWithType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attribute': json['attribute'],
        'colorizer': ColorizerFromJSON(json['colorizer']),
        'type': json['type'],
    };
}

export function DerivedColorWithTypeToJSON(value?: DerivedColorWithType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attribute': value.attribute,
        'colorizer': ColorizerToJSON(value.colorizer),
        'type': value.type,
    };
}

