/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FeatureDataType = {
    Category: 'category',
    Int: 'int',
    Float: 'float',
    Text: 'text',
    Bool: 'bool',
    DateTime: 'dateTime'
} as const;
export type FeatureDataType = typeof FeatureDataType[keyof typeof FeatureDataType];


export function FeatureDataTypeFromJSON(json: any): FeatureDataType {
    return FeatureDataTypeFromJSONTyped(json, false);
}

export function FeatureDataTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureDataType {
    return json as FeatureDataType;
}

export function FeatureDataTypeToJSON(value?: FeatureDataType | null): any {
    return value as any;
}

