/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DateTimeParseFormat } from './DateTimeParseFormat';
import {
    DateTimeParseFormatFromJSON,
    DateTimeParseFormatFromJSONTyped,
    DateTimeParseFormatToJSON,
} from './DateTimeParseFormat';
import type { TimeReference } from './TimeReference';
import {
    TimeReferenceFromJSON,
    TimeReferenceFromJSONTyped,
    TimeReferenceToJSON,
} from './TimeReference';

/**
 * 
 * @export
 * @interface GdalSourceTimePlaceholder
 */
export interface GdalSourceTimePlaceholder {
    /**
     * 
     * @type {DateTimeParseFormat}
     * @memberof GdalSourceTimePlaceholder
     */
    format: DateTimeParseFormat;
    /**
     * 
     * @type {TimeReference}
     * @memberof GdalSourceTimePlaceholder
     */
    reference: TimeReference;
}

/**
 * Check if a given object implements the GdalSourceTimePlaceholder interface.
 */
export function instanceOfGdalSourceTimePlaceholder(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "format" in value;
    isInstance = isInstance && "reference" in value;

    return isInstance;
}

export function GdalSourceTimePlaceholderFromJSON(json: any): GdalSourceTimePlaceholder {
    return GdalSourceTimePlaceholderFromJSONTyped(json, false);
}

export function GdalSourceTimePlaceholderFromJSONTyped(json: any, ignoreDiscriminator: boolean): GdalSourceTimePlaceholder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'format': DateTimeParseFormatFromJSON(json['format']),
        'reference': TimeReferenceFromJSON(json['reference']),
    };
}

export function GdalSourceTimePlaceholderToJSON(value?: GdalSourceTimePlaceholder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'format': DateTimeParseFormatToJSON(value.format),
        'reference': TimeReferenceToJSON(value.reference),
    };
}

