/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Coordinate2D } from './Coordinate2D';
import {
    Coordinate2DFromJSON,
    Coordinate2DFromJSONTyped,
    Coordinate2DToJSON,
} from './Coordinate2D';

/**
 * 
 * @export
 * @interface GdalDatasetGeoTransform
 */
export interface GdalDatasetGeoTransform {
    /**
     * 
     * @type {Coordinate2D}
     * @memberof GdalDatasetGeoTransform
     */
    originCoordinate: Coordinate2D;
    /**
     * 
     * @type {number}
     * @memberof GdalDatasetGeoTransform
     */
    xPixelSize: number;
    /**
     * 
     * @type {number}
     * @memberof GdalDatasetGeoTransform
     */
    yPixelSize: number;
}

/**
 * Check if a given object implements the GdalDatasetGeoTransform interface.
 */
export function instanceOfGdalDatasetGeoTransform(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "originCoordinate" in value;
    isInstance = isInstance && "xPixelSize" in value;
    isInstance = isInstance && "yPixelSize" in value;

    return isInstance;
}

export function GdalDatasetGeoTransformFromJSON(json: any): GdalDatasetGeoTransform {
    return GdalDatasetGeoTransformFromJSONTyped(json, false);
}

export function GdalDatasetGeoTransformFromJSONTyped(json: any, ignoreDiscriminator: boolean): GdalDatasetGeoTransform {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'originCoordinate': Coordinate2DFromJSON(json['originCoordinate']),
        'xPixelSize': json['xPixelSize'],
        'yPixelSize': json['yPixelSize'],
    };
}

export function GdalDatasetGeoTransformToJSON(value?: GdalDatasetGeoTransform | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'originCoordinate': Coordinate2DToJSON(value.originCoordinate),
        'xPixelSize': value.xPixelSize,
        'yPixelSize': value.yPixelSize,
    };
}

