/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GdalDatasetParameters } from './GdalDatasetParameters';
import {
    GdalDatasetParametersFromJSON,
    GdalDatasetParametersFromJSONTyped,
    GdalDatasetParametersToJSON,
} from './GdalDatasetParameters';
import type { GdalSourceTimePlaceholder } from './GdalSourceTimePlaceholder';
import {
    GdalSourceTimePlaceholderFromJSON,
    GdalSourceTimePlaceholderFromJSONTyped,
    GdalSourceTimePlaceholderToJSON,
} from './GdalSourceTimePlaceholder';
import type { RasterResultDescriptor } from './RasterResultDescriptor';
import {
    RasterResultDescriptorFromJSON,
    RasterResultDescriptorFromJSONTyped,
    RasterResultDescriptorToJSON,
} from './RasterResultDescriptor';
import type { TimeInterval } from './TimeInterval';
import {
    TimeIntervalFromJSON,
    TimeIntervalFromJSONTyped,
    TimeIntervalToJSON,
} from './TimeInterval';
import type { TimeStep } from './TimeStep';
import {
    TimeStepFromJSON,
    TimeStepFromJSONTyped,
    TimeStepToJSON,
} from './TimeStep';

/**
 * 
 * @export
 * @interface GdalMetaDataRegularWithType
 */
export interface GdalMetaDataRegularWithType {
    /**
     * 
     * @type {number}
     * @memberof GdalMetaDataRegularWithType
     */
    cacheTtl?: number;
    /**
     * 
     * @type {TimeInterval}
     * @memberof GdalMetaDataRegularWithType
     */
    dataTime: TimeInterval;
    /**
     * 
     * @type {GdalDatasetParameters}
     * @memberof GdalMetaDataRegularWithType
     */
    params: GdalDatasetParameters;
    /**
     * 
     * @type {RasterResultDescriptor}
     * @memberof GdalMetaDataRegularWithType
     */
    resultDescriptor: RasterResultDescriptor;
    /**
     * 
     * @type {TimeStep}
     * @memberof GdalMetaDataRegularWithType
     */
    step: TimeStep;
    /**
     * 
     * @type {{ [key: string]: GdalSourceTimePlaceholder; }}
     * @memberof GdalMetaDataRegularWithType
     */
    timePlaceholders: { [key: string]: GdalSourceTimePlaceholder; };
    /**
     * 
     * @type {string}
     * @memberof GdalMetaDataRegularWithType
     */
    type: GdalMetaDataRegularWithTypeTypeEnum;
}


/**
 * @export
 */
export const GdalMetaDataRegularWithTypeTypeEnum = {
    GdalMetaDataRegular: 'GdalMetaDataRegular'
} as const;
export type GdalMetaDataRegularWithTypeTypeEnum = typeof GdalMetaDataRegularWithTypeTypeEnum[keyof typeof GdalMetaDataRegularWithTypeTypeEnum];


/**
 * Check if a given object implements the GdalMetaDataRegularWithType interface.
 */
export function instanceOfGdalMetaDataRegularWithType(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "dataTime" in value;
    isInstance = isInstance && "params" in value;
    isInstance = isInstance && "resultDescriptor" in value;
    isInstance = isInstance && "step" in value;
    isInstance = isInstance && "timePlaceholders" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function GdalMetaDataRegularWithTypeFromJSON(json: any): GdalMetaDataRegularWithType {
    return GdalMetaDataRegularWithTypeFromJSONTyped(json, false);
}

export function GdalMetaDataRegularWithTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): GdalMetaDataRegularWithType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cacheTtl': !exists(json, 'cacheTtl') ? undefined : json['cacheTtl'],
        'dataTime': TimeIntervalFromJSON(json['dataTime']),
        'params': GdalDatasetParametersFromJSON(json['params']),
        'resultDescriptor': RasterResultDescriptorFromJSON(json['resultDescriptor']),
        'step': TimeStepFromJSON(json['step']),
        'timePlaceholders': (mapValues(json['timePlaceholders'], GdalSourceTimePlaceholderFromJSON)),
        'type': json['type'],
    };
}

export function GdalMetaDataRegularWithTypeToJSON(value?: GdalMetaDataRegularWithType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cacheTtl': value.cacheTtl,
        'dataTime': TimeIntervalToJSON(value.dataTime),
        'params': GdalDatasetParametersToJSON(value.params),
        'resultDescriptor': RasterResultDescriptorToJSON(value.resultDescriptor),
        'step': TimeStepToJSON(value.step),
        'timePlaceholders': (mapValues(value.timePlaceholders, GdalSourceTimePlaceholderToJSON)),
        'type': value.type,
    };
}

