/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RasterPropertiesEntryType } from './RasterPropertiesEntryType';
import {
    RasterPropertiesEntryTypeFromJSON,
    RasterPropertiesEntryTypeFromJSONTyped,
    RasterPropertiesEntryTypeToJSON,
} from './RasterPropertiesEntryType';
import type { RasterPropertiesKey } from './RasterPropertiesKey';
import {
    RasterPropertiesKeyFromJSON,
    RasterPropertiesKeyFromJSONTyped,
    RasterPropertiesKeyToJSON,
} from './RasterPropertiesKey';

/**
 * 
 * @export
 * @interface GdalMetadataMapping
 */
export interface GdalMetadataMapping {
    /**
     * 
     * @type {RasterPropertiesKey}
     * @memberof GdalMetadataMapping
     */
    sourceKey: RasterPropertiesKey;
    /**
     * 
     * @type {RasterPropertiesKey}
     * @memberof GdalMetadataMapping
     */
    targetKey: RasterPropertiesKey;
    /**
     * 
     * @type {RasterPropertiesEntryType}
     * @memberof GdalMetadataMapping
     */
    targetType: RasterPropertiesEntryType;
}

/**
 * Check if a given object implements the GdalMetadataMapping interface.
 */
export function instanceOfGdalMetadataMapping(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "sourceKey" in value;
    isInstance = isInstance && "targetKey" in value;
    isInstance = isInstance && "targetType" in value;

    return isInstance;
}

export function GdalMetadataMappingFromJSON(json: any): GdalMetadataMapping {
    return GdalMetadataMappingFromJSONTyped(json, false);
}

export function GdalMetadataMappingFromJSONTyped(json: any, ignoreDiscriminator: boolean): GdalMetadataMapping {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sourceKey': RasterPropertiesKeyFromJSON(json['source_key']),
        'targetKey': RasterPropertiesKeyFromJSON(json['target_key']),
        'targetType': RasterPropertiesEntryTypeFromJSON(json['target_type']),
    };
}

export function GdalMetadataMappingToJSON(value?: GdalMetadataMapping | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'source_key': RasterPropertiesKeyToJSON(value.sourceKey),
        'target_key': RasterPropertiesKeyToJSON(value.targetKey),
        'target_type': RasterPropertiesEntryTypeToJSON(value.targetType),
    };
}

