/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const GetMapFormat = {
    ImagePng: 'image/png'
} as const;
export type GetMapFormat = typeof GetMapFormat[keyof typeof GetMapFormat];


export function GetMapFormatFromJSON(json: any): GetMapFormat {
    return GetMapFormatFromJSONTyped(json, false);
}

export function GetMapFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMapFormat {
    return json as GetMapFormat;
}

export function GetMapFormatToJSON(value?: GetMapFormat | null): any {
    return value as any;
}

