/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InternalDataId
 */
export interface InternalDataId {
    /**
     * 
     * @type {string}
     * @memberof InternalDataId
     */
    datasetId: string;
    /**
     * 
     * @type {string}
     * @memberof InternalDataId
     */
    type: InternalDataIdTypeEnum;
}


/**
 * @export
 */
export const InternalDataIdTypeEnum = {
    Internal: 'internal',
    External: 'external'
} as const;
export type InternalDataIdTypeEnum = typeof InternalDataIdTypeEnum[keyof typeof InternalDataIdTypeEnum];


/**
 * Check if a given object implements the InternalDataId interface.
 */
export function instanceOfInternalDataId(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "datasetId" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function InternalDataIdFromJSON(json: any): InternalDataId {
    return InternalDataIdFromJSONTyped(json, false);
}

export function InternalDataIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalDataId {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'datasetId': json['datasetId'],
        'type': json['type'],
    };
}

export function InternalDataIdToJSON(value?: InternalDataId | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'datasetId': value.datasetId,
        'type': value.type,
    };
}

