/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LayerResource
 */
export interface LayerResource {
    /**
     * 
     * @type {string}
     * @memberof LayerResource
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof LayerResource
     */
    type: LayerResourceTypeEnum;
}


/**
 * @export
 */
export const LayerResourceTypeEnum = {
    Layer: 'layer'
} as const;
export type LayerResourceTypeEnum = typeof LayerResourceTypeEnum[keyof typeof LayerResourceTypeEnum];


/**
 * Check if a given object implements the LayerResource interface.
 */
export function instanceOfLayerResource(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function LayerResourceFromJSON(json: any): LayerResource {
    return LayerResourceFromJSONTyped(json, false);
}

export function LayerResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): LayerResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
    };
}

export function LayerResourceToJSON(value?: LayerResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': value.type,
    };
}

