/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LayerCollectionResourceId
 */
export interface LayerCollectionResourceId {
    /**
     * 
     * @type {string}
     * @memberof LayerCollectionResourceId
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof LayerCollectionResourceId
     */
    type: LayerCollectionResourceIdTypeEnum;
}


/**
 * @export
 */
export const LayerCollectionResourceIdTypeEnum = {
    LayerCollection: 'LayerCollection'
} as const;
export type LayerCollectionResourceIdTypeEnum = typeof LayerCollectionResourceIdTypeEnum[keyof typeof LayerCollectionResourceIdTypeEnum];


/**
 * Check if a given object implements the LayerCollectionResourceId interface.
 */
export function instanceOfLayerCollectionResourceId(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function LayerCollectionResourceIdFromJSON(json: any): LayerCollectionResourceId {
    return LayerCollectionResourceIdFromJSONTyped(json, false);
}

export function LayerCollectionResourceIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): LayerCollectionResourceId {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
    };
}

export function LayerCollectionResourceIdToJSON(value?: LayerCollectionResourceId | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': value.type,
    };
}

