/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LayerResourceId
 */
export interface LayerResourceId {
    /**
     * 
     * @type {string}
     * @memberof LayerResourceId
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof LayerResourceId
     */
    type: LayerResourceIdTypeEnum;
}


/**
 * @export
 */
export const LayerResourceIdTypeEnum = {
    Layer: 'Layer'
} as const;
export type LayerResourceIdTypeEnum = typeof LayerResourceIdTypeEnum[keyof typeof LayerResourceIdTypeEnum];


/**
 * Check if a given object implements the LayerResourceId interface.
 */
export function instanceOfLayerResourceId(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function LayerResourceIdFromJSON(json: any): LayerResourceId {
    return LayerResourceIdFromJSONTyped(json, false);
}

export function LayerResourceIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): LayerResourceId {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
    };
}

export function LayerResourceIdToJSON(value?: LayerResourceId | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': value.type,
    };
}

