/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StrokeParam } from './StrokeParam';
import {
    StrokeParamFromJSON,
    StrokeParamFromJSONTyped,
    StrokeParamToJSON,
} from './StrokeParam';
import type { TextSymbology } from './TextSymbology';
import {
    TextSymbologyFromJSON,
    TextSymbologyFromJSONTyped,
    TextSymbologyToJSON,
} from './TextSymbology';

/**
 * 
 * @export
 * @interface LineSymbology
 */
export interface LineSymbology {
    /**
     * 
     * @type {boolean}
     * @memberof LineSymbology
     */
    autoSimplified: boolean;
    /**
     * 
     * @type {StrokeParam}
     * @memberof LineSymbology
     */
    stroke: StrokeParam;
    /**
     * 
     * @type {TextSymbology}
     * @memberof LineSymbology
     */
    text?: TextSymbology | null;
}

/**
 * Check if a given object implements the LineSymbology interface.
 */
export function instanceOfLineSymbology(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "autoSimplified" in value;
    isInstance = isInstance && "stroke" in value;

    return isInstance;
}

export function LineSymbologyFromJSON(json: any): LineSymbology {
    return LineSymbologyFromJSONTyped(json, false);
}

export function LineSymbologyFromJSONTyped(json: any, ignoreDiscriminator: boolean): LineSymbology {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'autoSimplified': json['autoSimplified'],
        'stroke': StrokeParamFromJSON(json['stroke']),
        'text': !exists(json, 'text') ? undefined : TextSymbologyFromJSON(json['text']),
    };
}

export function LineSymbologyToJSON(value?: LineSymbology | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'autoSimplified': value.autoSimplified,
        'stroke': StrokeParamToJSON(value.stroke),
        'text': TextSymbologyToJSON(value.text),
    };
}

