/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelIdResourceId
 */
export interface ModelIdResourceId {
    /**
     * 
     * @type {string}
     * @memberof ModelIdResourceId
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ModelIdResourceId
     */
    type: ModelIdResourceIdTypeEnum;
}


/**
 * @export
 */
export const ModelIdResourceIdTypeEnum = {
    ModelId: 'ModelId'
} as const;
export type ModelIdResourceIdTypeEnum = typeof ModelIdResourceIdTypeEnum[keyof typeof ModelIdResourceIdTypeEnum];


/**
 * Check if a given object implements the ModelIdResourceId interface.
 */
export function instanceOfModelIdResourceId(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function ModelIdResourceIdFromJSON(json: any): ModelIdResourceId {
    return ModelIdResourceIdFromJSONTyped(json, false);
}

export function ModelIdResourceIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelIdResourceId {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
    };
}

export function ModelIdResourceIdToJSON(value?: ModelIdResourceId | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': value.type,
    };
}

