/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Coordinate2D } from './Coordinate2D';
import {
    Coordinate2DFromJSON,
    Coordinate2DFromJSONTyped,
    Coordinate2DToJSON,
} from './Coordinate2D';

/**
 * 
 * @export
 * @interface MultiPolygon
 */
export interface MultiPolygon {
    /**
     * 
     * @type {Array<Array<Array<Coordinate2D>>>}
     * @memberof MultiPolygon
     */
    polygons: Array<Array<Array<Coordinate2D>>>;
}

/**
 * Check if a given object implements the MultiPolygon interface.
 */
export function instanceOfMultiPolygon(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "polygons" in value;

    return isInstance;
}

export function MultiPolygonFromJSON(json: any): MultiPolygon {
    return MultiPolygonFromJSONTyped(json, false);
}

export function MultiPolygonFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiPolygon {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'polygons': json['polygons'],
    };
}

export function MultiPolygonToJSON(value?: MultiPolygon | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'polygons': value.polygons,
    };
}

