/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Permission } from './Permission';
import {
    PermissionFromJSON,
    PermissionFromJSONTyped,
    PermissionToJSON,
} from './Permission';
import type { Resource } from './Resource';
import {
    ResourceFromJSON,
    ResourceFromJSONTyped,
    ResourceToJSON,
} from './Resource';

/**
 * Request for adding a new permission to the given role on the given resource
 * @export
 * @interface PermissionRequest
 */
export interface PermissionRequest {
    /**
     * 
     * @type {Permission}
     * @memberof PermissionRequest
     */
    permission: Permission;
    /**
     * 
     * @type {Resource}
     * @memberof PermissionRequest
     */
    resource: Resource;
    /**
     * 
     * @type {string}
     * @memberof PermissionRequest
     */
    roleId: string;
}

/**
 * Check if a given object implements the PermissionRequest interface.
 */
export function instanceOfPermissionRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "permission" in value;
    isInstance = isInstance && "resource" in value;
    isInstance = isInstance && "roleId" in value;

    return isInstance;
}

export function PermissionRequestFromJSON(json: any): PermissionRequest {
    return PermissionRequestFromJSONTyped(json, false);
}

export function PermissionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'permission': PermissionFromJSON(json['permission']),
        'resource': ResourceFromJSON(json['resource']),
        'roleId': json['roleId'],
    };
}

export function PermissionRequestToJSON(value?: PermissionRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'permission': PermissionToJSON(value.permission),
        'resource': ResourceToJSON(value.resource),
        'roleId': value.roleId,
    };
}

