/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PlotOutputFormat = {
    JsonPlain: 'JsonPlain',
    JsonVega: 'JsonVega',
    ImagePng: 'ImagePng'
} as const;
export type PlotOutputFormat = typeof PlotOutputFormat[keyof typeof PlotOutputFormat];


export function PlotOutputFormatFromJSON(json: any): PlotOutputFormat {
    return PlotOutputFormatFromJSONTyped(json, false);
}

export function PlotOutputFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlotOutputFormat {
    return json as PlotOutputFormat;
}

export function PlotOutputFormatToJSON(value?: PlotOutputFormat | null): any {
    return value as any;
}

