/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BoundingBox2D } from './BoundingBox2D';
import {
    BoundingBox2DFromJSON,
    BoundingBox2DFromJSONTyped,
    BoundingBox2DToJSON,
} from './BoundingBox2D';
import type { SpatialResolution } from './SpatialResolution';
import {
    SpatialResolutionFromJSON,
    SpatialResolutionFromJSONTyped,
    SpatialResolutionToJSON,
} from './SpatialResolution';
import type { TimeInterval } from './TimeInterval';
import {
    TimeIntervalFromJSON,
    TimeIntervalFromJSONTyped,
    TimeIntervalToJSON,
} from './TimeInterval';

/**
 * A spatio-temporal rectangle with a specified resolution
 * @export
 * @interface PlotQueryRectangle
 */
export interface PlotQueryRectangle {
    /**
     * 
     * @type {BoundingBox2D}
     * @memberof PlotQueryRectangle
     */
    spatialBounds: BoundingBox2D;
    /**
     * 
     * @type {SpatialResolution}
     * @memberof PlotQueryRectangle
     */
    spatialResolution: SpatialResolution;
    /**
     * 
     * @type {TimeInterval}
     * @memberof PlotQueryRectangle
     */
    timeInterval: TimeInterval;
}

/**
 * Check if a given object implements the PlotQueryRectangle interface.
 */
export function instanceOfPlotQueryRectangle(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "spatialBounds" in value;
    isInstance = isInstance && "spatialResolution" in value;
    isInstance = isInstance && "timeInterval" in value;

    return isInstance;
}

export function PlotQueryRectangleFromJSON(json: any): PlotQueryRectangle {
    return PlotQueryRectangleFromJSONTyped(json, false);
}

export function PlotQueryRectangleFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlotQueryRectangle {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'spatialBounds': BoundingBox2DFromJSON(json['spatialBounds']),
        'spatialResolution': SpatialResolutionFromJSON(json['spatialResolution']),
        'timeInterval': TimeIntervalFromJSON(json['timeInterval']),
    };
}

export function PlotQueryRectangleToJSON(value?: PlotQueryRectangle | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'spatialBounds': BoundingBox2DToJSON(value.spatialBounds),
        'spatialResolution': SpatialResolutionToJSON(value.spatialResolution),
        'timeInterval': TimeIntervalToJSON(value.timeInterval),
    };
}

