/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ColorParam } from './ColorParam';
import {
    ColorParamFromJSON,
    ColorParamFromJSONTyped,
    ColorParamToJSON,
} from './ColorParam';
import type { NumberParam } from './NumberParam';
import {
    NumberParamFromJSON,
    NumberParamFromJSONTyped,
    NumberParamToJSON,
} from './NumberParam';
import type { StrokeParam } from './StrokeParam';
import {
    StrokeParamFromJSON,
    StrokeParamFromJSONTyped,
    StrokeParamToJSON,
} from './StrokeParam';
import type { TextSymbology } from './TextSymbology';
import {
    TextSymbologyFromJSON,
    TextSymbologyFromJSONTyped,
    TextSymbologyToJSON,
} from './TextSymbology';

/**
 * 
 * @export
 * @interface PointSymbologyWithType
 */
export interface PointSymbologyWithType {
    /**
     * 
     * @type {ColorParam}
     * @memberof PointSymbologyWithType
     */
    fillColor: ColorParam;
    /**
     * 
     * @type {NumberParam}
     * @memberof PointSymbologyWithType
     */
    radius: NumberParam;
    /**
     * 
     * @type {StrokeParam}
     * @memberof PointSymbologyWithType
     */
    stroke: StrokeParam;
    /**
     * 
     * @type {TextSymbology}
     * @memberof PointSymbologyWithType
     */
    text?: TextSymbology | null;
    /**
     * 
     * @type {string}
     * @memberof PointSymbologyWithType
     */
    type: PointSymbologyWithTypeTypeEnum;
}


/**
 * @export
 */
export const PointSymbologyWithTypeTypeEnum = {
    Point: 'point'
} as const;
export type PointSymbologyWithTypeTypeEnum = typeof PointSymbologyWithTypeTypeEnum[keyof typeof PointSymbologyWithTypeTypeEnum];


/**
 * Check if a given object implements the PointSymbologyWithType interface.
 */
export function instanceOfPointSymbologyWithType(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "fillColor" in value;
    isInstance = isInstance && "radius" in value;
    isInstance = isInstance && "stroke" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function PointSymbologyWithTypeFromJSON(json: any): PointSymbologyWithType {
    return PointSymbologyWithTypeFromJSONTyped(json, false);
}

export function PointSymbologyWithTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PointSymbologyWithType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fillColor': ColorParamFromJSON(json['fillColor']),
        'radius': NumberParamFromJSON(json['radius']),
        'stroke': StrokeParamFromJSON(json['stroke']),
        'text': !exists(json, 'text') ? undefined : TextSymbologyFromJSON(json['text']),
        'type': json['type'],
    };
}

export function PointSymbologyWithTypeToJSON(value?: PointSymbologyWithType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fillColor': ColorParamToJSON(value.fillColor),
        'radius': NumberParamToJSON(value.radius),
        'stroke': StrokeParamToJSON(value.stroke),
        'text': TextSymbologyToJSON(value.text),
        'type': value.type,
    };
}

