/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectResourceId
 */
export interface ProjectResourceId {
    /**
     * 
     * @type {string}
     * @memberof ProjectResourceId
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectResourceId
     */
    type: ProjectResourceIdTypeEnum;
}


/**
 * @export
 */
export const ProjectResourceIdTypeEnum = {
    Project: 'Project'
} as const;
export type ProjectResourceIdTypeEnum = typeof ProjectResourceIdTypeEnum[keyof typeof ProjectResourceIdTypeEnum];


/**
 * Check if a given object implements the ProjectResourceId interface.
 */
export function instanceOfProjectResourceId(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function ProjectResourceIdFromJSON(json: any): ProjectResourceId {
    return ProjectResourceIdFromJSONTyped(json, false);
}

export function ProjectResourceIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectResourceId {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
    };
}

export function ProjectResourceIdToJSON(value?: ProjectResourceId | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': value.type,
    };
}

