/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProviderLayerCollectionId
 */
export interface ProviderLayerCollectionId {
    /**
     * 
     * @type {string}
     * @memberof ProviderLayerCollectionId
     */
    collectionId: string;
    /**
     * 
     * @type {string}
     * @memberof ProviderLayerCollectionId
     */
    providerId: string;
}

/**
 * Check if a given object implements the ProviderLayerCollectionId interface.
 */
export function instanceOfProviderLayerCollectionId(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "collectionId" in value;
    isInstance = isInstance && "providerId" in value;

    return isInstance;
}

export function ProviderLayerCollectionIdFromJSON(json: any): ProviderLayerCollectionId {
    return ProviderLayerCollectionIdFromJSONTyped(json, false);
}

export function ProviderLayerCollectionIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderLayerCollectionId {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'collectionId': json['collectionId'],
        'providerId': json['providerId'],
    };
}

export function ProviderLayerCollectionIdToJSON(value?: ProviderLayerCollectionId | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'collectionId': value.collectionId,
        'providerId': value.providerId,
    };
}

