/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Measurement } from './Measurement';
import {
    MeasurementFromJSON,
    MeasurementFromJSONTyped,
    MeasurementToJSON,
} from './Measurement';

/**
 * 
 * @export
 * @interface RasterBandDescriptor
 */
export interface RasterBandDescriptor {
    /**
     * 
     * @type {Measurement}
     * @memberof RasterBandDescriptor
     */
    measurement: Measurement;
    /**
     * 
     * @type {string}
     * @memberof RasterBandDescriptor
     */
    name: string;
}

/**
 * Check if a given object implements the RasterBandDescriptor interface.
 */
export function instanceOfRasterBandDescriptor(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "measurement" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function RasterBandDescriptorFromJSON(json: any): RasterBandDescriptor {
    return RasterBandDescriptorFromJSONTyped(json, false);
}

export function RasterBandDescriptorFromJSONTyped(json: any, ignoreDiscriminator: boolean): RasterBandDescriptor {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'measurement': MeasurementFromJSON(json['measurement']),
        'name': json['name'],
    };
}

export function RasterBandDescriptorToJSON(value?: RasterBandDescriptor | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'measurement': MeasurementToJSON(value.measurement),
        'name': value.name,
    };
}

