/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServerInfo
 */
export interface ServerInfo {
    /**
     * 
     * @type {string}
     * @memberof ServerInfo
     */
    buildDate: string;
    /**
     * 
     * @type {string}
     * @memberof ServerInfo
     */
    commitHash: string;
    /**
     * 
     * @type {string}
     * @memberof ServerInfo
     */
    features: string;
    /**
     * 
     * @type {string}
     * @memberof ServerInfo
     */
    version: string;
}

/**
 * Check if a given object implements the ServerInfo interface.
 */
export function instanceOfServerInfo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "buildDate" in value;
    isInstance = isInstance && "commitHash" in value;
    isInstance = isInstance && "features" in value;
    isInstance = isInstance && "version" in value;

    return isInstance;
}

export function ServerInfoFromJSON(json: any): ServerInfo {
    return ServerInfoFromJSONTyped(json, false);
}

export function ServerInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'buildDate': json['buildDate'],
        'commitHash': json['commitHash'],
        'features': json['features'],
        'version': json['version'],
    };
}

export function ServerInfoToJSON(value?: ServerInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'buildDate': value.buildDate,
        'commitHash': value.commitHash,
        'features': value.features,
        'version': value.version,
    };
}

