/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A spatial reference authority that is part of a spatial reference definition
 * @export
 */
export const SpatialReferenceAuthority = {
    Epsg: 'EPSG',
    SrOrg: 'SR-ORG',
    Iau2000: 'IAU2000',
    Esri: 'ESRI'
} as const;
export type SpatialReferenceAuthority = typeof SpatialReferenceAuthority[keyof typeof SpatialReferenceAuthority];


export function SpatialReferenceAuthorityFromJSON(json: any): SpatialReferenceAuthority {
    return SpatialReferenceAuthorityFromJSONTyped(json, false);
}

export function SpatialReferenceAuthorityFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpatialReferenceAuthority {
    return json as SpatialReferenceAuthority;
}

export function SpatialReferenceAuthorityToJSON(value?: SpatialReferenceAuthority | null): any {
    return value as any;
}

