/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ColorParam } from './ColorParam';
import {
    ColorParamFromJSON,
    ColorParamFromJSONTyped,
    ColorParamToJSON,
} from './ColorParam';
import type { NumberParam } from './NumberParam';
import {
    NumberParamFromJSON,
    NumberParamFromJSONTyped,
    NumberParamToJSON,
} from './NumberParam';

/**
 * 
 * @export
 * @interface StrokeParam
 */
export interface StrokeParam {
    /**
     * 
     * @type {ColorParam}
     * @memberof StrokeParam
     */
    color: ColorParam;
    /**
     * 
     * @type {NumberParam}
     * @memberof StrokeParam
     */
    width: NumberParam;
}

/**
 * Check if a given object implements the StrokeParam interface.
 */
export function instanceOfStrokeParam(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "color" in value;
    isInstance = isInstance && "width" in value;

    return isInstance;
}

export function StrokeParamFromJSON(json: any): StrokeParam {
    return StrokeParamFromJSONTyped(json, false);
}

export function StrokeParamFromJSONTyped(json: any, ignoreDiscriminator: boolean): StrokeParam {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'color': ColorParamFromJSON(json['color']),
        'width': NumberParamFromJSON(json['width']),
    };
}

export function StrokeParamToJSON(value?: StrokeParam | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'color': ColorParamToJSON(value.color),
        'width': NumberParamToJSON(value.width),
    };
}

