/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TaskStatus } from './TaskStatus';
import {
    TaskStatusFromJSON,
    TaskStatusFromJSONTyped,
    TaskStatusToJSON,
} from './TaskStatus';

/**
 * 
 * @export
 * @interface TaskStatusWithId
 */
export type TaskStatusWithId = { taskId: string } & TaskStatus;

export interface _TaskStatusWithId /* extends TaskStatus */ {
    /**
     * 
     * @type {string}
     * @memberof TaskStatusWithId
     */
    taskId: string;
}



/**
 * Check if a given object implements the TaskStatusWithId interface.
 */
export function instanceOfTaskStatusWithId(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "taskId" in value;

    return isInstance;
}

export function TaskStatusWithIdFromJSON(json: any): TaskStatusWithId {
    return TaskStatusWithIdFromJSONTyped(json, false);
}

export function TaskStatusWithIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskStatusWithId {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...TaskStatusFromJSONTyped(json, ignoreDiscriminator),
        'taskId': json['taskId'],
    };
}

export function TaskStatusWithIdToJSON(value?: TaskStatusWithId | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...TaskStatusToJSON(value),
        'taskId': value.taskId,
    };
}

