/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TaskFilter } from './TaskFilter';
import {
    TaskFilterFromJSON,
    TaskFilterFromJSONTyped,
    TaskFilterToJSON,
} from './TaskFilter';

/**
 * 
 * @export
 * @interface TaskListOptions
 */
export interface TaskListOptions {
    /**
     * 
     * @type {TaskFilter}
     * @memberof TaskListOptions
     */
    filter?: TaskFilter | null;
    /**
     * 
     * @type {number}
     * @memberof TaskListOptions
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskListOptions
     */
    offset?: number;
}

/**
 * Check if a given object implements the TaskListOptions interface.
 */
export function instanceOfTaskListOptions(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TaskListOptionsFromJSON(json: any): TaskListOptions {
    return TaskListOptionsFromJSONTyped(json, false);
}

export function TaskListOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskListOptions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'filter': !exists(json, 'filter') ? undefined : TaskFilterFromJSON(json['filter']),
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'offset': !exists(json, 'offset') ? undefined : json['offset'],
    };
}

export function TaskListOptionsToJSON(value?: TaskListOptions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'filter': TaskFilterToJSON(value.filter),
        'limit': value.limit,
        'offset': value.offset,
    };
}

