/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ColorParam } from './ColorParam';
import {
    ColorParamFromJSON,
    ColorParamFromJSONTyped,
    ColorParamToJSON,
} from './ColorParam';
import type { StrokeParam } from './StrokeParam';
import {
    StrokeParamFromJSON,
    StrokeParamFromJSONTyped,
    StrokeParamToJSON,
} from './StrokeParam';

/**
 * 
 * @export
 * @interface TextSymbology
 */
export interface TextSymbology {
    /**
     * 
     * @type {string}
     * @memberof TextSymbology
     */
    attribute: string;
    /**
     * 
     * @type {ColorParam}
     * @memberof TextSymbology
     */
    fillColor: ColorParam;
    /**
     * 
     * @type {StrokeParam}
     * @memberof TextSymbology
     */
    stroke: StrokeParam;
}

/**
 * Check if a given object implements the TextSymbology interface.
 */
export function instanceOfTextSymbology(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "attribute" in value;
    isInstance = isInstance && "fillColor" in value;
    isInstance = isInstance && "stroke" in value;

    return isInstance;
}

export function TextSymbologyFromJSON(json: any): TextSymbology {
    return TextSymbologyFromJSONTyped(json, false);
}

export function TextSymbologyFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextSymbology {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attribute': json['attribute'],
        'fillColor': ColorParamFromJSON(json['fillColor']),
        'stroke': StrokeParamFromJSON(json['stroke']),
    };
}

export function TextSymbologyToJSON(value?: TextSymbology | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attribute': value.attribute,
        'fillColor': ColorParamToJSON(value.fillColor),
        'stroke': StrokeParamToJSON(value.stroke),
    };
}

