/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MultiLineString } from './MultiLineString';
import {
    MultiLineStringFromJSON,
    MultiLineStringFromJSONTyped,
    MultiLineStringToJSON,
} from './MultiLineString';

/**
 * 
 * @export
 * @interface TypedGeometryOneOf2
 */
export interface TypedGeometryOneOf2 {
    /**
     * 
     * @type {MultiLineString}
     * @memberof TypedGeometryOneOf2
     */
    multiLineString: MultiLineString;
}

/**
 * Check if a given object implements the TypedGeometryOneOf2 interface.
 */
export function instanceOfTypedGeometryOneOf2(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "multiLineString" in value;

    return isInstance;
}

export function TypedGeometryOneOf2FromJSON(json: any): TypedGeometryOneOf2 {
    return TypedGeometryOneOf2FromJSONTyped(json, false);
}

export function TypedGeometryOneOf2FromJSONTyped(json: any, ignoreDiscriminator: boolean): TypedGeometryOneOf2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'multiLineString': MultiLineStringFromJSON(json['MultiLineString']),
    };
}

export function TypedGeometryOneOf2ToJSON(value?: TypedGeometryOneOf2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'MultiLineString': MultiLineStringToJSON(value.multiLineString),
    };
}

