/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UnixTimeStampType } from './UnixTimeStampType';
import {
    UnixTimeStampTypeFromJSON,
    UnixTimeStampTypeFromJSONTyped,
    UnixTimeStampTypeToJSON,
} from './UnixTimeStampType';

/**
 * 
 * @export
 * @interface UnixTimeStampOgrSourceTimeFormat
 */
export interface UnixTimeStampOgrSourceTimeFormat {
    /**
     * 
     * @type {string}
     * @memberof UnixTimeStampOgrSourceTimeFormat
     */
    format: UnixTimeStampOgrSourceTimeFormatFormatEnum;
    /**
     * 
     * @type {UnixTimeStampType}
     * @memberof UnixTimeStampOgrSourceTimeFormat
     */
    timestampType: UnixTimeStampType;
}


/**
 * @export
 */
export const UnixTimeStampOgrSourceTimeFormatFormatEnum = {
    UnixTimeStamp: 'unixTimeStamp'
} as const;
export type UnixTimeStampOgrSourceTimeFormatFormatEnum = typeof UnixTimeStampOgrSourceTimeFormatFormatEnum[keyof typeof UnixTimeStampOgrSourceTimeFormatFormatEnum];


/**
 * Check if a given object implements the UnixTimeStampOgrSourceTimeFormat interface.
 */
export function instanceOfUnixTimeStampOgrSourceTimeFormat(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "format" in value;
    isInstance = isInstance && "timestampType" in value;

    return isInstance;
}

export function UnixTimeStampOgrSourceTimeFormatFromJSON(json: any): UnixTimeStampOgrSourceTimeFormat {
    return UnixTimeStampOgrSourceTimeFormatFromJSONTyped(json, false);
}

export function UnixTimeStampOgrSourceTimeFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnixTimeStampOgrSourceTimeFormat {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'format': json['format'],
        'timestampType': UnixTimeStampTypeFromJSON(json['timestampType']),
    };
}

export function UnixTimeStampOgrSourceTimeFormatToJSON(value?: UnixTimeStampOgrSourceTimeFormat | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'format': value.format,
        'timestampType': UnixTimeStampTypeToJSON(value.timestampType),
    };
}

