/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BoundingBox2D } from './BoundingBox2D';
import {
    BoundingBox2DFromJSON,
    BoundingBox2DFromJSONTyped,
    BoundingBox2DToJSON,
} from './BoundingBox2D';
import type { TimeInterval } from './TimeInterval';
import {
    TimeIntervalFromJSON,
    TimeIntervalFromJSONTyped,
    TimeIntervalToJSON,
} from './TimeInterval';
import type { VectorColumnInfo } from './VectorColumnInfo';
import {
    VectorColumnInfoFromJSON,
    VectorColumnInfoFromJSONTyped,
    VectorColumnInfoToJSON,
} from './VectorColumnInfo';
import type { VectorDataType } from './VectorDataType';
import {
    VectorDataTypeFromJSON,
    VectorDataTypeFromJSONTyped,
    VectorDataTypeToJSON,
} from './VectorDataType';

/**
 * 
 * @export
 * @interface VectorResultDescriptorWithType
 */
export interface VectorResultDescriptorWithType {
    /**
     * 
     * @type {BoundingBox2D}
     * @memberof VectorResultDescriptorWithType
     */
    bbox?: BoundingBox2D | null;
    /**
     * 
     * @type {{ [key: string]: VectorColumnInfo; }}
     * @memberof VectorResultDescriptorWithType
     */
    columns: { [key: string]: VectorColumnInfo; };
    /**
     * 
     * @type {VectorDataType}
     * @memberof VectorResultDescriptorWithType
     */
    dataType: VectorDataType;
    /**
     * 
     * @type {string}
     * @memberof VectorResultDescriptorWithType
     */
    spatialReference: string;
    /**
     * 
     * @type {TimeInterval}
     * @memberof VectorResultDescriptorWithType
     */
    time?: TimeInterval | null;
    /**
     * 
     * @type {string}
     * @memberof VectorResultDescriptorWithType
     */
    type: VectorResultDescriptorWithTypeTypeEnum;
}


/**
 * @export
 */
export const VectorResultDescriptorWithTypeTypeEnum = {
    Vector: 'vector'
} as const;
export type VectorResultDescriptorWithTypeTypeEnum = typeof VectorResultDescriptorWithTypeTypeEnum[keyof typeof VectorResultDescriptorWithTypeTypeEnum];


/**
 * Check if a given object implements the VectorResultDescriptorWithType interface.
 */
export function instanceOfVectorResultDescriptorWithType(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "columns" in value;
    isInstance = isInstance && "dataType" in value;
    isInstance = isInstance && "spatialReference" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function VectorResultDescriptorWithTypeFromJSON(json: any): VectorResultDescriptorWithType {
    return VectorResultDescriptorWithTypeFromJSONTyped(json, false);
}

export function VectorResultDescriptorWithTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VectorResultDescriptorWithType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bbox': !exists(json, 'bbox') ? undefined : BoundingBox2DFromJSON(json['bbox']),
        'columns': (mapValues(json['columns'], VectorColumnInfoFromJSON)),
        'dataType': VectorDataTypeFromJSON(json['dataType']),
        'spatialReference': json['spatialReference'],
        'time': !exists(json, 'time') ? undefined : TimeIntervalFromJSON(json['time']),
        'type': json['type'],
    };
}

export function VectorResultDescriptorWithTypeToJSON(value?: VectorResultDescriptorWithType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bbox': BoundingBox2DToJSON(value.bbox),
        'columns': (mapValues(value.columns, VectorColumnInfoToJSON)),
        'dataType': VectorDataTypeToJSON(value.dataType),
        'spatialReference': value.spatialReference,
        'time': TimeIntervalToJSON(value.time),
        'type': value.type,
    };
}

