/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.8.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const WfsVersion = {
    _200: '2.0.0'
} as const;
export type WfsVersion = typeof WfsVersion[keyof typeof WfsVersion];


export function WfsVersionFromJSON(json: any): WfsVersion {
    return WfsVersionFromJSONTyped(json, false);
}

export function WfsVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): WfsVersion {
    return json as WfsVersion;
}

export function WfsVersionToJSON(value?: WfsVersion | null): any {
    return value as any;
}

