/* tslint:disable */
/* eslint-disable */
/**
 * Geo Engine Pro API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.7.0
 * Contact: dev@geoengine.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PermissionRequest,
} from '../models/index';
import {
    PermissionRequestFromJSON,
    PermissionRequestToJSON,
} from '../models/index';

export interface AddPermissionHandlerRequest {
    permissionRequest: PermissionRequest;
}

export interface RemovePermissionHandlerRequest {
    permissionRequest: PermissionRequest;
}

/**
 * 
 */
export class PermissionsApi extends runtime.BaseAPI {

    /**
     * Adds a new permission.
     * Adds a new permission.
     */
    async addPermissionHandlerRaw(requestParameters: AddPermissionHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.permissionRequest === null || requestParameters.permissionRequest === undefined) {
            throw new runtime.RequiredError('permissionRequest','Required parameter requestParameters.permissionRequest was null or undefined when calling addPermissionHandler.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("session_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/permissions`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PermissionRequestToJSON(requestParameters.permissionRequest),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Adds a new permission.
     * Adds a new permission.
     */
    async addPermissionHandler(requestParameters: AddPermissionHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.addPermissionHandlerRaw(requestParameters, initOverrides);
    }

    /**
     * Removes an existing permission.
     * Removes an existing permission.
     */
    async removePermissionHandlerRaw(requestParameters: RemovePermissionHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.permissionRequest === null || requestParameters.permissionRequest === undefined) {
            throw new runtime.RequiredError('permissionRequest','Required parameter requestParameters.permissionRequest was null or undefined when calling removePermissionHandler.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("session_token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/permissions`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: PermissionRequestToJSON(requestParameters.permissionRequest),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes an existing permission.
     * Removes an existing permission.
     */
    async removePermissionHandler(requestParameters: RemovePermissionHandlerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.removePermissionHandlerRaw(requestParameters, initOverrides);
    }

}
